# Generated by Django 5.0.7 on 2024-07-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('gamemode', models.CharField(choices=[('multipleChoice', 'Multiple Choice'), ('freeWriting', 'Free Writing'), ('withPictures', 'With Pictures')], max_length=50)),
                ('category', models.CharField(choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('geography', 'Geography'), ('popMusic', 'Pop Music'), ('rockMusic', 'Rock Music'), ('electroMusic', 'Electro Music'), ('classicalMusic', 'Classical Music'), ('rapMusic', 'Rap Music'), ('movies', 'Movies'), ('tvShows', 'TV Shows'), ('literature', 'Literature'), ('animeManga', 'Anime & Manga'), ('computerScience', 'Computer Science'), ('videoGames', 'Video Games'), ('sports', 'Sports'), ('eSports', 'E-Sports'), ('languages', 'Languages'), ('history', 'History'), ('misc', 'Misc.')], max_length=50)),
                ('number_of_questions', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('description', models.TextField()),
            ],
        ),
    ]
