# Generated by Django 5.0.7 on 2024-07-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(max_length=300)),
                ('answer1', models.CharField(max_length=300)),
                ('answer2', models.CharField(max_length=300)),
                ('answer3', models.CharField(max_length=300)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz')),
            ],
        ),
    ]
