# Generated by Django 5.0.7 on 2024-07-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='gamemode',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
    ]
