# Generated by Django 5.0.7 on 2024-07-26 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quiz_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('general', 'General Knowledge'), ('books', 'Entertainment: Books'), ('film', 'Entertainment: Film'), ('music', 'Entertainment: Music'), ('musicals', 'Entertainment: Musicals & Theatres'), ('television', 'Entertainment: Television'), ('videoGames', 'Entertainment: Video Games'), ('boardGames', 'Entertainment: Board Games'), ('nature', 'Science & Nature'), ('computers', 'Science: Computers'), ('mathematics', 'Science: Mathematics'), ('mythology', 'Mythology'), ('sports', 'Sports'), ('geography', 'Geography'), ('history', 'History'), ('politics', 'Politics'), ('art', 'Art'), ('celebrities', 'Celebrities'), ('animals', 'Animals'), ('vehicles', 'Vehicles'), ('comics', 'Entertainment: Comics'), ('gadgets', 'Science: Gadgets'), ('anime', 'Entertainment: Japanese Anime & Manga'), ('cartoons', 'Entertainment: Cartoon & Animations')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(max_length=300)),
                ('incorrect_answer1', models.CharField(max_length=300)),
                ('incorrect_answer2', models.CharField(max_length=300)),
                ('incorrect_answer3', models.CharField(blank=True, max_length=300, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz')),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
